name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      - name: Inject KV Namespace IDs
        run: |
          sed -i "s/SIEVE_DATA_ID/${{ secrets.SIEVE_DATA_ID }}/g" wrangler.toml
          sed -i "s/SIEVE_DATA_PREVIEW_ID/${{ secrets.SIEVE_DATA_PREVIEW_ID }}/g" wrangler.toml

      - name: Deploy to Cloudflare Workers
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        run: npx wrangler deploy

      - name: Upload Examples
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        run: |
          # Upload Templates
          if [ -d "./examples/templates" ]; then
            for file in ./examples/templates/*; do
              if [ -f "$file" ]; then
                filename=$(basename "$file")
                echo "Uploading template: $filename"
                npx wrangler kv key put "template:$filename" --path="$file" --namespace-id ${{ secrets.SIEVE_DATA_ID }} --remote
              fi
            done
          fi

          # Upload Lists
          if [ -d "./examples/lists" ]; then
            for file in ./examples/lists/*; do
              if [ -f "$file" ]; then
                filename=$(basename "$file")
                echo "Uploading list: $filename"
                npx wrangler kv key put "list:$filename" --path="$file" --namespace-id ${{ secrets.SIEVE_DATA_ID }} --remote
              fi
            done
          fi
